CREATE TABLE policy_info (
    id integer NOT NULL,
    state_id integer NOT NULL,
    policy_grade character varying(255),
    climate_plan character varying(255),
    portfolio_standard character varying(255),
    pace character varying(255),
    clean_vehicle character varying(255),
    green_pricing character varying(255),
    home_solar character varying(255),
    community_solar character varying(255),
    community_choice character varying(255),
    energy_standard character varying(255),
    utility_board character varying(255),
    resident_count integer,
    resident_mwh integer
);

INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (1, 1, 'D', 'Revoked ', NULL, 'Authorized**', NULL, NULL, 'D', 'F', NULL, NULL, NULL, 277706, 1919293);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (2, 2, 'F', NULL, NULL, 'Authorized*', NULL, NULL, 'F', 'F', NULL, NULL, NULL, 2211497, 32847886);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (3, 3, 'D', NULL, NULL, 'Yes', NULL, ' ', 'D', 'F', NULL, 'Mandatory', NULL, 1374238, 19087597);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (4, 4, 'C', 'Released', '15% by 2025', 'No', 'Clean Energy Vehicle Incentives', ' ', 'C', 'F', NULL, 'Mandatory', NULL, 2867418, 34476376);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (5, 5, 'A', 'Released', '100% by 2045', 'Yes', 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives', ' ', 'A', 'B', 'Yes', 'Mandatory', NULL, 14110761, 89059042);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (6, 6, 'A', 'Released', '30% by 2020', 'Yes', 'Electric Vehicle Financial Incentives', 'Yes', 'A', 'C', NULL, 'Mandatory', NULL, 2321459, 19086993);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (7, 7, 'A', 'Released', '48% by 2030', 'Yes', 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives', 'Yes/Retail', 'A', 'B', NULL, 'Mandatory', NULL, 1512363, 12843176);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (8, 8, 'A', 'Released', '100% by 2032', 'Yes', 'Electric Vehicle Financial Incentives', 'Retail', 'A', 'B', NULL, 'Voluntary', NULL, 265924, 2284987);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (9, 9, 'B', 'Updating ', '25% by 2030', 'Yes', 'Electric Vehicle Financial Incentives', 'Yes/Retail', 'B', 'D', NULL, 'Voluntary', NULL, 434126, 5041549);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (10, 10, 'C', 'Released', NULL, 'Yes', 'Clean Energy Vehicle Incentives', ' ', 'C', 'F', NULL, 'Voluntary', NULL, 9403116, 125300441);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (11, 11, 'D', NULL, NULL, 'Yes', 'Clean Energy Vehicle Incentives', ' ', 'D', 'F', NULL, NULL, NULL, 4318851, 59224428);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (12, 12, 'B', 'Released', '100% by 2050', 'Authorized*', NULL, ' ', 'B', 'C', NULL, 'Mandatory', NULL, 450721, 2710605);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (13, 13, 'C', 'Released', 'Not updated', 'No', NULL, 'Yes', 'C', 'F', NULL, 'Mandatory', NULL, 1341456, 14400940);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (14, 14, 'D', NULL, NULL, 'No', 'Clean Energy Vehicle Incentives', ' ', 'D', 'F', NULL, NULL, NULL, 726975, 8178074);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (15, 15, 'B', 'Released', '25% by 2025', 'Authorized*', 'Clean Energy Vehicle Incentives', 'Retail', 'B', 'B', 'Yes', 'Mandatory', 'Yes', 5274278, 47036972);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (16, 16, 'C', NULL, 'Voluntary', 'No', 'Clean Energy Vehicle Incentives', ' ', 'C', 'F', NULL, 'Repealed', NULL, 2800195, 33779557);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (17, 17, 'F', NULL, 'Voluntary', 'No', 'Clean Energy Vehicle Incentives', NULL, 'F', 'F', NULL, NULL, 'Yes', 1219892, 13741099);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (18, 18, 'F', 'Released', NULL, 'Authorized*', NULL, NULL, 'F', 'F', NULL, 'Voluntary', NULL, 1966517, 27532177);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (19, 19, 'F', NULL, NULL, 'No', 'Clean Energy Vehicle Incentives', NULL, 'F', 'F', NULL, NULL, NULL, 2059502, 31720591);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (20, 20, 'A', 'Released', '80% by 2050', 'Authorized*', 'Zero Emission Vehicle Standard', 'Retail', 'A', 'A', 'Yes', 'Mandatory', NULL, 2621532, 18811049);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (21, 21, 'A', 'Updating', '50% by 2030', 'Yes', 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives', 'Retail', 'A', 'B', NULL, 'Mandatory', NULL, 2362136, 27894485);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (22, 22, 'C', 'Updating ', '100% by 2050', 'Yes', 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives', 'Yes/Retail', 'B', 'B', NULL, 'Mandatory', NULL, 723682, 4896533);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (23, 23, 'F', 'Released', '15% by 2021', 'Yes', NULL, ' ', 'C', 'F', NULL, 'Mandatory', NULL, 4331640, 34887079);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (24, 24, 'A', 'Updating', '31.5% by 2020', 'Yes', NULL, 'Yes', 'A', 'B', NULL, 'Mandatory', NULL, 2376211, 22432917);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (25, 25, 'C', NULL, '15% by 2021', 'Yes', NULL, NULL, 'C', 'F', NULL, 'Voluntary', NULL, 2733986, 36716412);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (26, 26, 'F', NULL, NULL, 'No', NULL, NULL, 'F', 'F', NULL, NULL, NULL, 1281915, 19229336);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (27, 27, 'C', 'Updating ', '16% by 2015', 'No', 'Clean Energy Vehicle Incentives', 'Yes', 'C', 'F', NULL, NULL, NULL, 502129, 5080988);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (28, 28, 'C', 'Released', '12.5% by 2021', 'No', NULL, ' ', 'B', 'F', NULL, NULL, NULL, 4498644, 61009429);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (29, 29, 'F', NULL, 'Voluntary', 'No', NULL, NULL, 'D', 'F', NULL, NULL, NULL, 374816, 4989431);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (30, 30, 'D', NULL, NULL, 'Yes', 'Clean Energy Vehicle Incentives', NULL, 'D', 'F', NULL, NULL, NULL, 821507, 10096659);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (31, 31, 'A', 'Released', '25.2% 2025', 'Yes', NULL, 'Retail', 'C', 'C', 'Yes', 'Mandatory', NULL, 625750, 4576746);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (32, 32, 'A', 'Updating', '50% by 2030', 'Yes', 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives', 'Yes/Retail', 'B', 'C', 'Yes', 'Mandatory', NULL, 3600957, 29305540);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (33, 33, 'B', 'Released', '100% by 2045', 'Authorized*', NULL, 'Yes', 'A', 'F', NULL, 'Mandatory', NULL, 880508, 6744639);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (34, 34, 'B', 'Developing', '50% by 2030', 'Yes', 'Clean Energy Vehicle Incentives', ' ', 'B', 'C', NULL, NULL, NULL, 1197178, 13386525);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (35, 35, 'A', 'Updating', '50% by 2030', 'Yes', 'Zero Emission Vehicle Standard', 'Retail', 'B', 'B', 'Yes', 'Mandatory', NULL, 7101931, 51033008);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (36, 36, 'C', NULL, '12.5% by 2026', 'Yes', 'Clean Energy Vehicle Incentives', 'Retail', 'B', 'F', 'Yes', 'Mandatory', NULL, 4467198, 49268444);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (37, 37, 'F', NULL, 'Voluntary', 'Authorized*', 'Clean Energy Vehicle Incentives', NULL, 'F', 'F', NULL, NULL, NULL, 1713922, 23541227);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (38, 38, 'B', 'Released', '50% by 2040', 'Yes', 'Zero Emission Vehicle Standard', ' ', 'B', 'C', NULL, 'Voluntary', 'Yes', 1748595, 18862728);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (39, 39, 'C', 'Released', '18% by 2021', 'Authorized*', 'Electric Vehicle Financial Incentives', 'Retail', 'C', 'F', NULL, 'Mandatory', NULL, 5322708, 54829560);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (40, 40, 'A', 'Released', '38.8% by 2035', 'Yes', 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives', 'Retail', 'A', 'B', 'Yes', 'Mandatory', NULL, 437618, 3041032);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (41, 41, 'C', 'Released', 'Voluntary', 'No', 'Clean Energy Vehicle Incentives', NULL, 'C', 'F', NULL, NULL, NULL, 2286994, 31732512);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (42, 42, 'F', NULL, 'Voluntary', 'No', NULL, NULL, 'D', 'F', NULL, 'Voluntary', NULL, 391339, 4894563);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (43, 43, 'F', NULL, NULL, 'No', 'Clean Energy Vehicle Incentives', NULL, 'F', 'F', NULL, 'Voluntary', NULL, 2882992, 44381957);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (44, 44, 'C', NULL, 'Not updated', 'Yes', 'Clean Energy Vehicle Incentives', 'Retail', 'C', 'F', NULL, 'Mandatory', NULL, 11074754, 156206367);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (45, 45, 'D', NULL, 'Voluntary', 'Authorized*', 'Clean Energy Vehicle Incentives', ' ', 'B', 'F', NULL, NULL, NULL, 1062623, 9448637);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (46, 46, 'D', 'Released', 'Voluntary', 'Yes', 'Clean Energy Vehicle Incentives', 'Yes', 'C', 'F', 'Yes', 'Voluntary', NULL, 3426471, 47886897);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (47, 47, 'B', 'Released', '75% by 2032', 'Authorized*', 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives', 'Yes', 'B', 'B', NULL, 'Mandatory', NULL, 307509, 2051388);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (48, 48, 'C', 'Released', '100% by 2045', 'No', 'Electric Vehicle Financial Incentives', 'Yes', 'C', 'C', NULL, 'Mandatory', NULL, 3056825, 35072781);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (49, 49, 'C', 'Updating', '10% by 2015', 'Yes', 'Clean Energy Vehicle Incentives', ' ', 'D', 'C', NULL, 'Mandatory', 'Yes', 2668462, 22157659);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (50, 50, 'D', NULL, 'Repealed', 'No', NULL, NULL, 'C', 'F', NULL, NULL, NULL, 850158, 11587335);
INSERT INTO public.policy_info (id, state_id, policy_grade, climate_plan, portfolio_standard, pace, clean_vehicle, green_pricing, home_solar, community_solar, community_choice, energy_standard, utility_board, resident_count, resident_mwh) VALUES (51, 51, 'D', NULL, NULL, 'Authorized*', NULL, NULL, 'D', 'F', NULL, NULL, NULL, 261192, 2637424);

ALTER TABLE policy_info ADD CONSTRAINT policy_info_pk PRIMARY KEY (id);

ALTER TABLE policy_info ADD CONSTRAINT policy_info_fk0 FOREIGN KEY (state_id) REFERENCES public.state(id);