CREATE TABLE "policy_language" (
	"id" serial NOT NULL,
	"policy_id" int NOT NULL,
	"short_info" varchar NOT NULL,
	"long_info" varchar NOT NULL,
	"petition_info" varchar NOT NULL,
	CONSTRAINT "policy_language_pk" PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);
[AllowHtml]

INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (1, 1, 'Climate Action Plans are state- city- or region-wide plans to reduce greenhouse gas emissions and increase resilience. They usually include emissions reduction targets and steps to reach those goals through energy efficiency, land use, green energy, and transportation.', 
'This is the longer Climate Action Plan info text for the pop-up. To be changed, content copied here to show approximate length. Climate Action Plans are state- city- or region-wide plans to reduce greenhouse gas emissions and increase resilience. They usually include emissions reduction targets and steps to reach those goals through energy efficiency, land use, green energy, and transportation.
Climate Action Plans are state- city- or region-wide plans to reduce greenhouse gas emissions and increase resilience. They usually include emissions reduction targets and steps to reach those goals through energy efficiency, land use, green energy, and transportation.
Climate Action Plans are state- city- or region-wide plans to reduce greenhouse gas emissions and increase resilience. They usually include emissions reduction targets and steps to reach those goals through energy efficiency, land use, green energy, and transportation.', 'In order to more effectively mitigate and adapt to the urgent climate crisis, [STATE] should adopt a comprehensive Climate Action Plan. This is the petition text for climate action plans. Climate Action Plans are state- city- or region-wide plans to reduce greenhouse gas emissions and increase resilience. They usually include emissions reduction targets and steps to reach those goals through energy efficiency, land use, green energy, and transportation.');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (2, 2, 'Renewable Portfolio Standards require utilities to source a percentage of their electricity from renewable or "alternative" sources. (Some states include nuclear or natural gas as "alternative" carbon-free energy sources.)', '<b>Renewable Portfolio Standards (RPS) or Renewable Energy Standards</b> are state-level policies that require utility companies to source a percentage of their electricity from renewable or “alternative” sources. (Some states include nuclear or natural gas as “alternative” carbon-free energy sources). RPS policies usually include a target date (such as 2035) in order to give utilities time to transition, and sometimes they include different goals or requirements for smaller utility companies or co-ops. RPSs are laws that are voted on by state representatives and passed by governors.

Utility companies can meet RPS requirements by building new renewable generation like solar or wind farms to source their energy from, or by buying Renewable Energy Certificates/Credits (RECs) from independent suppliers that signify that green energy was generated, added to the grid, and used. Utilities are usually required to buy bundled RECs, which means they buy the electricity generated as well as the green certification. Renewable Portfolio Standards may also require utilities to buy renewable energy from within their own state or region. This ensures that the economic benefits of green energy - as well as the health benefits, in many cases - stay local.

Renewable Portfolio Standards were originally created to encourage the development of renewable energy when it was more expensive. Now, renewable energy is cheaper and in demand, and is on track to exceed modest goals set by states. However, energy companies can still make more profit by running fossil fuel plants that they have already built than by investing in new renewable energy, so we will not reach 100% renewable energy with the free market alone.

In order to mitigate climate change and eliminate dangerous air pollution, we need to transition to 100% renewable energy. A Renewable Portfolio Standard of 100% by 2035 would turn a state’s electricity sector green, and help eliminate 30% (or more, if combined with other policies) of the state’s greenhouse gas emissions.', 
'[STATE] should accelerate our transition to clean, carbon-free energy by adopting a Renewable Portfolio Standard of 100% renewable energy by 2035. This policy should include a requirement that energy is purchased from regional suppliers, and should be designed in collaboration with local communities, so that [STATE] benefits from the economic and health benefits of transitioning away from dangerous, polluting fossil fuel power.

The goal of 100% renewable by 2035 is ambitious, but we are running out of time to address the worst impacts of climate change, and the fossil fuel pollution that is already harming our health and environment every day. According to EPA research, pollution from the fossil fuel energy industry causes billions of dollars of public health harms in the US every year. As a resident of [STATE], I care where my energy comes from, and I believe it should be from 100% green, renewable sources.');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (3, 3, 'Property Assessed Clean Energy (PACE) is a financing program that provides low-interest loans for property owners to increase energy efficiency of their buildings, or install solar panels.', 
'In order to incentivize energy efficience in our state, [STATE] should adopt Property Assessed Clean Energy (PACE) standards and programs. This is the petition text for PACE. [Property Assessed Clean Energy (PACE) is a financing program that provides low-interest loans for property owners to increase energy efficiency of their buildings, or install solar panels.]In order to incentivize energy efficience in our state, [STATE] should adopt Property Assessed Clean Energy (PACE) standards and programs. This is the petition text for PACE. [Property Assessed Clean Energy (PACE) is a financing program that provides low-interest loans for property owners to increase energy efficiency of their buildings, or install solar panels.]

In order to incentivize energy efficience in our state, [STATE] should adopt Property Assessed Clean Energy (PACE) standards and programs. This is the petition text for PACE. [Property Assessed Clean Energy (PACE) is a financing program that provides low-interest loans for property owners to increase energy efficiency of their buildings, or install solar panels.]', 
'In order to incentivize energy efficience in our state, [STATE] should adopt Property Assessed Clean Energy (PACE) standards and programs. This is the petition text for PACE. [Property Assessed Clean Energy (PACE) is a financing program that provides low-interest loans for property owners to increase energy efficiency of their buildings, or install solar panels.');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (4, 4, 'Clean Vehicle Policies or Zero Emissions Vehicle (ZEV) policies encourage the sale and ownership of electric or hybrid vehicles, often through consumer incentives (like tax credits or rebates), or quotas for vehicle sellers.', 
'Clean Vehicle Policies or Zero Emissions Vehicle (ZEV) policies encourage the sale and ownership of electric or hybrid vehicles, often through consumer incentives (like tax credits or rebates), or quotas for vehicle sellers.Clean Vehicle Policies or Zero Emissions Vehicle (ZEV) policies encourage the sale and ownership of electric or hybrid vehicles, often through consumer incentives (like tax credits or rebates), or quotas for vehicle sellers.

Clean Vehicle Policies or Zero Emissions Vehicle (ZEV) policies encourage the sale and ownership of electric or hybrid vehicles, often through consumer incentives (like tax credits or rebates), or quotas for vehicle sellers.', 
'Transportation is responsible for 28.2% of greenhouse gas emissions in the US. In order to address the urgent climate crisis, [STATE] should adopt strict zero emissions vehicle standards, along with clean energy policies, so that we can do our part to reduce emissions. Current policies in some states encourage electric vehicle sales by offering tax incentives to consumers, or requiring manufacturers to offer a certain percentage of zero emissions vehicles for sale. These are good transitional policies, but I believe that [STATE] can go further to help protect clean air and a livable future. We need bold policies and strong leadership to help us transition away from harmful, polluting gas vehicles. In addition to increasing electric car charging infrastructure and creating incentives for consumers to trade in gas-powered vehicles for hybrid or electric vehicles, [STATE] should follow France’s lead and phase out the sale of gas-powered cars and light trucks entirely by 2040. ');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (5, 5, 'Green Pricing Mandates require utility companies to offer green pricing programs to their customers. They may also include requirements for where the green energy is sourced from, and whether utilities are allowed to profit from these programs.', 
'Green Pricing Mandates require utility companies to offer green pricing programs to their customers. They may also include requirements for where the green energy is sourced from, and whether utilities are allowed to profit from these programs.Green Pricing Mandates require utility companies to offer green pricing programs to their customers. They may also include requirements for where the green energy is sourced from, and whether utilities are allowed to profit from these programs.

Green Pricing Mandates require utility companies to offer green pricing programs to their customers. They may also include requirements for where the green energy is sourced from, and whether utilities are allowed to profit from these programs.', 
'Energy consumers in our state deserve to have the right to choose green energy and help push our energy system toward 100% renewables. [STATE] should adopt a Green Pricing Mandate that requires utility companies to offer customers a 100% green power option. This is the Green pricing mandate petition text. [Green Pricing Mandates require utility companies to offer green pricing programs to their customers. They may also include requirements for where the green energy is sourced from, and whether utilities are allowed to profit from these programs.]');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (6, 6, 'Some states make it easier or more difficult to install solar on your home and get the financial and energy benefits of generating green power. Net metering policies, incentives, and ease of interconnection all increase home solar rights.', 
'
Some states make it easier or more difficult to install solar on your home and get the financial and energy benefits of generating green power. Net metering policies, incentives, and ease of interconnection all increase home solar rights.Some states make it easier or more difficult to install solar on your home and get the financial and energy benefits of generating green power. Net metering policies, incentives, and ease of interconnection all increase home solar rights.

Some states make it easier or more difficult to install solar on your home and get the financial and energy benefits of generating green power. Net metering policies, incentives, and ease of interconnection all increase home solar rights.', 
'A network of home solar panels in [STATE] can reduce our emissions and help increase resiliency and energy independence. [STATE] should support Home Solar Rights by implementing these policies. This is the petition text. Some states make it easier or more difficult to install solar on your home and get the financial and energy benefits of generating green power. Net metering policies, incentives, and ease of interconnection all increase home solar rights.]');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (7, 7, 'Community Solar is a model for shared ownership of solar gardens. Neighborhoods and groups can cooperatively own shares of distributed solar generation and receive the financial benefits of generating power. Policies like Community Choice Aggregation, Net Metering, and State Renewable Portfolio Standard carve-outs make community solar possible.', 
'Community Solar is a model for shared ownership of solar gardens. Neighborhoods and groups can cooperatively own shares of distributed solar generation and receive the financial benefits of generating power. Policies like Community Choice Aggregation, Net Metering, and State Renewable Portfolio Standard carve-outs make community solar possible. Community Solar is a model for shared ownership of solar gardens. Neighborhoods and groups can cooperatively own shares of distributed solar generation and receive the financial benefits of generating power. Policies like Community Choice Aggregation, Net Metering, and State Renewable Portfolio Standard carve-outs make community solar possible.

Community Solar is a model for shared ownership of solar gardens. Neighborhoods and groups can cooperatively own shares of distributed solar generation and receive the financial benefits of generating power. Policies like Community Choice Aggregation, Net Metering, and State Renewable Portfolio Standard carve-outs make community solar possible.', 
'Community Solar programs can help our state go greener while increasing resiliency and sharing the benefits of solar with more communities, including those who aren''t able to access individual rooftop solar. [STATE] should support community solar by implementing these policies. Petition text. Community Solar is a model for shared ownership of solar gardens. Neighborhoods and groups can cooperatively own shares of distributed solar generation and receive the financial benefits of generating power. Policies like Community Choice Aggregation, Net Metering, and State Renewable Portfolio Standard carve-outs make community solar possible.');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (8, 8, 'Community Choice Aggregation (CCA) allows communities and local governments to get energy from alternative suppliers, while still using the transmission and distribution services of the local utility company. This increases local control and allows communities to choose green power sources, even if the local utility does not.', 
'Community Choice Aggregation (CCA) allows communities and local governments to get energy from alternative suppliers, while still using the transmission and distribution services of the local utility company. This increases local control and allows communities to choose green power sources, even if the local utility does not.Community Choice Aggregation (CCA) allows communities and local governments to get energy from alternative suppliers, while still using the transmission and distribution services of the local utility company. This increases local control and allows communities to choose green power sources, even if the local utility does not.

Community Choice Aggregation (CCA) allows communities and local governments to get energy from alternative suppliers, while still using the transmission and distribution services of the local utility company. This increases local control and allows communities to choose green power sources, even if the local utility does not.', 

' [STATE] should adopt policies that allow for Community Choice Aggregation (CCA) for local energy supply. CCA allows communities and local governments to procure power from alternative suppliers, while still using the transmission and distribution services of the local utility company. This increases local control and allows communities to choose green power sources, even if the local utility does not. I believe that [STATE] residents deserve to have more of a say in where their electricity comes from. Fossil fuel energy contributes to the growing climate crisis, and produces dangerous air pollution that is harmful to our health. Decisions about where and how our energy is produced should not be left in the hands of utility companies, who continue to profit from fossil fuel power while the rest of us face the negative impacts. CCA would help empower local communities to choose what is right for them.');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (9, 9, 'Energy Efficiency Standards set goals for overall energy use reduction in a state, and include different strategies for achieving these goals, such as: demand-side management incentives, building codes, and consumer self-direction.', 
'Energy Efficiency Standards set goals for overall energy use reduction in a state, and include different strategies for achieving these goals, such as: demand-side management incentives, building codes, and consumer self-direction.Energy Efficiency Standards set goals for overall energy use reduction in a state, and include different strategies for achieving these goals, such as: demand-side management incentives, building codes, and consumer self-direction.

Energy Efficiency Standards set goals for overall energy use reduction in a state, and include different strategies for achieving these goals, such as: demand-side management incentives, building codes, and consumer self-direction.', 
'In order to reduce our energy use as a state and reduce our greenhouse gas emissions, [STATE] should adopt these Energy Efficiency Standards. This is the petition text. Energy Efficiency Standards set goals for overall energy use reduction in a state, and include different strategies for achieving these goals, such as: demand-side management incentives, building codes, and consumer self-direction.');
INSERT INTO policy_language (id, policy_id, short_info, long_info, petition_info) VALUES (10, 10, 'Citizens Utility Boards are independent state-level organizations that advocate for fair energy policy from a consumer perspective.', 'Citizens Utility Boards Longer Text

Citizens Utility Boards are independent state-level organizations that advocate for fair energy policy from a consumer perspective.Citizens Utility Boards are independent state-level organizations that advocate for fair energy policy from a consumer perspective.Citizens Utility Boards are independent state-level organizations that advocate for fair energy policy from a consumer perspective.

Citizens Utility Boards are independent state-level organizations that advocate for fair energy policy from a consumer perspective.', 'Energy policy affects us all, but consumers don''t have enough of a voice when it comes to deciding policy and setting rates in our state. [STATE] should create a Citizens Utility Board that does that stuff. This is the petition text. Citizens Utility Boards are independent state-level organizations that advocate for fair energy policy from a consumer perspective.');

ALTER TABLE policy_language ADD CONSTRAINT policy_language_fk0 FOREIGN KEY (policy_id) REFERENCES policy_name(id) ON DELETE CASCADE;

SELECT setval('policy_language_id_seq', (SELECT MAX(id) FROM policy_language)+1);
