CREATE TABLE "policy_info" (
	"id" serial NOT NULL,
	"state_id" int NOT NULL,
	"policy_id" int NOT NULL,
	"policy_data" varchar(255),
	CONSTRAINT "policy_info_pk" PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);

INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (1, 1, 1, 'Revoked ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (2, 1, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (3, 1, 3, 'Authorized**');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (4, 1, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (5, 1, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (6, 1, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (7, 1, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (8, 1, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (9, 1, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (10, 1, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (11, 2, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (12, 2, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (13, 2, 3, ' Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (14, 2, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (15, 2, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (16, 2, 6, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (17, 2, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (18, 2, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (19, 2, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (20, 2, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (21, 3, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (22, 3, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (23, 3, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (24, 3, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (25, 3, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (26, 3, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (27, 3, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (28, 3, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (29, 3, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (30, 3, 10, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (31, 4, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (32, 4, 2, '15% by 2025');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (33, 4, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (34, 4, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (35, 4, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (36, 4, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (37, 4, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (38, 4, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (39, 4, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (40, 4, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (41, 5, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (42, 5, 2, '100% by 2045');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (43, 5, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (44, 5, 4, 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (45, 5, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (46, 5, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (47, 5, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (48, 5, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (49, 5, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (50, 5, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (51, 6, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (52, 6, 2, '30% by 2020');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (53, 6, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (54, 6, 4, 'Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (55, 6, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (56, 6, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (57, 6, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (58, 6, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (59, 6, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (60, 6, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (61, 7, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (62, 7, 2, '48% by 2030');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (63, 7, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (64, 7, 4, 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (65, 7, 5, 'Yes/Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (66, 7, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (67, 7, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (68, 7, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (69, 7, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (70, 7, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (71, 8, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (72, 8, 2, '100% by 2032');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (73, 8, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (74, 8, 4, 'Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (75, 8, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (76, 8, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (77, 8, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (78, 8, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (79, 8, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (80, 8, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (81, 9, 1, 'Updating ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (82, 9, 2, '25% by 2030');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (83, 9, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (84, 9, 4, 'Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (85, 9, 5, 'Yes/Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (86, 9, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (87, 9, 7, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (88, 9, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (89, 9, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (90, 9, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (91, 10, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (92, 10, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (93, 10, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (94, 10, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (95, 10, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (96, 10, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (97, 10, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (98, 10, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (99, 10, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (100, 10, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (101, 11, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (102, 11, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (103, 11, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (104, 11, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (105, 11, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (106, 11, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (107, 11, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (108, 11, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (109, 11, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (110, 11, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (111, 12, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (112, 12, 2, '100% by 2050');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (113, 12, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (114, 12, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (115, 12, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (116, 12, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (117, 12, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (118, 12, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (119, 12, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (120, 12, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (121, 13, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (122, 13, 2, 'Not updated');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (123, 13, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (124, 13, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (125, 13, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (126, 13, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (127, 13, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (128, 13, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (129, 13, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (130, 13, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (131, 14, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (132, 14, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (133, 14, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (134, 14, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (135, 14, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (136, 14, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (137, 14, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (138, 14, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (139, 14, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (140, 14, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (141, 15, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (142, 15, 2, '25% by 2025');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (143, 15, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (144, 15, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (145, 15, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (146, 15, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (147, 15, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (148, 15, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (149, 15, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (150, 15, 10, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (151, 16, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (152, 16, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (153, 16, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (154, 16, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (155, 16, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (156, 16, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (157, 16, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (158, 16, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (159, 16, 9, 'Repealed');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (160, 16, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (161, 17, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (162, 17, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (163, 17, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (164, 17, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (165, 17, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (166, 17, 6, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (167, 17, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (168, 17, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (169, 17, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (170, 17, 10, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (171, 18, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (172, 18, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (173, 18, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (174, 18, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (175, 18, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (176, 18, 6, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (177, 18, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (178, 18, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (179, 18, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (180, 18, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (181, 19, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (182, 19, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (183, 19, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (184, 19, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (185, 19, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (186, 19, 6, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (187, 19, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (188, 19, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (189, 19, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (190, 19, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (191, 20, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (192, 20, 2, '80% by 2050');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (193, 20, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (194, 20, 4, 'Zero Emission Vehicle Standard');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (195, 20, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (196, 20, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (197, 20, 7, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (198, 20, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (199, 20, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (200, 20, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (201, 21, 1, 'Updating');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (202, 21, 2, '50% by 2030');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (203, 21, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (204, 21, 4, 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (205, 21, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (206, 21, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (207, 21, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (208, 21, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (209, 21, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (210, 21, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (211, 22, 1, 'Updating ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (212, 22, 2, '100% by 2050');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (213, 22, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (214, 22, 4, 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (215, 22, 5, 'Yes/Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (216, 22, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (217, 22, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (218, 22, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (219, 22, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (220, 22, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (221, 23, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (222, 23, 2, '15% by 2021');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (223, 23, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (224, 23, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (225, 23, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (226, 23, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (227, 23, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (228, 23, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (229, 23, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (230, 23, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (231, 24, 1, 'Updating');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (232, 24, 2, '31.5% by 2020');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (233, 24, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (234, 24, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (235, 24, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (236, 24, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (237, 24, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (238, 24, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (239, 24, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (240, 24, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (241, 25, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (242, 25, 2, '15% by 2021');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (243, 25, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (244, 25, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (245, 25, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (246, 25, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (247, 25, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (248, 25, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (249, 25, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (250, 25, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (251, 26, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (252, 26, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (253, 26, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (254, 26, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (255, 26, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (256, 26, 6, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (257, 26, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (258, 26, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (259, 26, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (260, 26, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (261, 27, 1, 'Updating ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (262, 27, 2, '16% by 2015');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (263, 27, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (264, 27, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (265, 27, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (266, 27, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (267, 27, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (268, 27, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (269, 27, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (270, 27, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (271, 28, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (272, 28, 2, '12.5% by 2021');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (273, 28, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (274, 28, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (275, 28, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (276, 28, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (277, 28, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (278, 28, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (279, 28, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (280, 28, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (281, 29, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (282, 29, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (283, 29, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (284, 29, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (285, 29, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (286, 29, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (287, 29, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (288, 29, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (289, 29, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (290, 29, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (291, 30, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (292, 30, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (293, 30, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (294, 30, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (295, 30, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (296, 30, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (297, 30, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (298, 30, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (299, 30, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (300, 30, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (301, 31, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (302, 31, 2, '25.2% 2025');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (303, 31, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (304, 31, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (305, 31, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (306, 31, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (307, 31, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (308, 31, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (309, 31, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (310, 31, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (311, 32, 1, 'Updating');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (312, 32, 2, '50% by 2030');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (313, 32, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (314, 32, 4, 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (315, 32, 5, 'Yes/Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (316, 32, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (317, 32, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (318, 32, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (319, 32, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (320, 32, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (321, 33, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (322, 33, 2, '100% by 2045');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (323, 33, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (324, 33, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (325, 33, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (326, 33, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (327, 33, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (328, 33, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (329, 33, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (330, 33, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (331, 34, 1, 'Developing');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (332, 34, 2, '50% by 2030');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (333, 34, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (334, 34, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (335, 34, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (336, 34, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (337, 34, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (338, 34, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (339, 34, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (340, 34, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (341, 35, 1, 'Updating');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (342, 35, 2, '50% by 2030');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (343, 35, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (344, 35, 4, 'Zero Emission Vehicle Standard');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (345, 35, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (346, 35, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (347, 35, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (348, 35, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (349, 35, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (350, 35, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (351, 36, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (352, 36, 2, '12.5% by 2026');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (353, 36, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (354, 36, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (355, 36, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (356, 36, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (357, 36, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (358, 36, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (359, 36, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (360, 36, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (361, 37, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (362, 37, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (363, 37, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (364, 37, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (365, 37, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (366, 37, 6, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (367, 37, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (368, 37, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (369, 37, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (370, 37, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (371, 38, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (372, 38, 2, '50% by 2040');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (373, 38, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (374, 38, 4, 'Zero Emission Vehicle Standard');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (375, 38, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (376, 38, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (377, 38, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (378, 38, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (379, 38, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (380, 38, 10, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (381, 39, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (382, 39, 2, '18% by 2021');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (383, 39, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (384, 39, 4, 'Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (385, 39, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (386, 39, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (387, 39, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (388, 39, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (389, 39, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (390, 39, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (391, 40, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (392, 40, 2, '38.8% by 2035');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (393, 40, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (394, 40, 4, 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (395, 40, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (396, 40, 6, 'A');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (397, 40, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (398, 40, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (399, 40, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (400, 40, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (401, 41, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (402, 41, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (403, 41, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (404, 41, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (405, 41, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (406, 41, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (407, 41, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (408, 41, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (409, 41, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (410, 41, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (411, 42, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (412, 42, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (413, 42, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (414, 42, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (415, 42, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (416, 42, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (417, 42, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (418, 42, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (419, 42, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (420, 42, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (421, 43, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (422, 43, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (423, 43, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (424, 43, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (425, 43, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (426, 43, 6, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (427, 43, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (428, 43, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (429, 43, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (430, 43, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (431, 44, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (432, 44, 2, 'Not updated');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (433, 44, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (434, 44, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (435, 44, 5, 'Retail');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (436, 44, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (437, 44, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (438, 44, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (439, 44, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (440, 44, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (441, 45, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (442, 45, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (443, 45, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (444, 45, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (445, 45, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (446, 45, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (447, 45, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (448, 45, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (449, 45, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (450, 45, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (451, 46, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (452, 46, 2, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (453, 46, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (454, 46, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (455, 46, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (456, 46, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (457, 46, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (458, 46, 8, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (459, 46, 9, 'Voluntary');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (460, 46, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (461, 47, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (462, 47, 2, '75% by 2032');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (463, 47, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (464, 47, 4, 'Zero Emission Vehicle Standard & Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (465, 47, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (466, 47, 6, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (467, 47, 7, 'B');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (468, 47, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (469, 47, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (470, 47, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (471, 48, 1, 'Released');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (472, 48, 2, '100% by 2045');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (473, 48, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (474, 48, 4, 'Electric Vehicle Financial Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (475, 48, 5, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (476, 48, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (477, 48, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (478, 48, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (479, 48, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (480, 48, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (481, 49, 1, 'Updating');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (482, 49, 2, '10% by 2015');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (483, 49, 3, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (484, 49, 4, 'Clean Energy Vehicle Incentives');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (485, 49, 5, ' ');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (486, 49, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (487, 49, 7, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (488, 49, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (489, 49, 9, 'Mandatory');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (490, 49, 10, 'Yes');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (491, 50, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (492, 50, 2, 'Repealed');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (493, 50, 3, 'No');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (494, 50, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (495, 50, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (496, 50, 6, 'C');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (497, 50, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (498, 50, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (499, 50, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (500, 50, 10, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (501, 51, 1, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (502, 51, 2, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (503, 51, 3, 'Authorized*');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (504, 51, 4, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (505, 51, 5, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (506, 51, 6, 'D');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (507, 51, 7, 'F');
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (508, 51, 8, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (509, 51, 9, NULL);
INSERT INTO policy_info (id, state_id, policy_id, policy_data) VALUES (510, 51, 10, NULL);


ALTER TABLE policy_info ADD CONSTRAINT policy_info_fk0 FOREIGN KEY (state_id) REFERENCES "state"(id) ON DELETE CASCADE;

ALTER TABLE policy_info ADD CONSTRAINT policy_info_fk1 FOREIGN KEY (policy_id) REFERENCES "policy_name"(id) ON DELETE CASCADE;